version: "3"
services:
  ci-web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 80:80
    networks:
      - travellist
      - external

  mysql:
    image: mysql:5.7
    container_name: ci4-database
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'pas123'
      MYSQL_DATABASE: 'itemdb'
    ports:
        - 3306:3306
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password  
    networks:
      - travellist
      - external

networks:
    travellist:
        driver: bridge
    external: