apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: ci-deploy
  name: ci-deploy
  namespace: default
  
spec:
  
  ports:
  - nodePort: 31356
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ci-deploy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
